### PR TITLE
Integrate FMOD into main

### PR DESCRIPTION
**Pull request by VeryPuzzling**
# Changlog
- Added the FMOD Engine to Godot through a 3rd party plugin (FMOD is available through the FMOD EULA (https://www.fmod.com/legal & https://www.fmod.com/attribution) and FMOD for Godot is under the MIT license (https://github.com/alessandrofama/fmod-for-godot))
- Recreated all current audio events in FMOD
- Constructed FMOD banks for everything
- Converted various things to FMOD
  - Title Screen (now looping!)
  - Credits Music
  - Door SFX
  - Holding Cells (set up but not implemented)
    - Danger transition available through the Studio**Global**ParameterTrigger node & class and activeGuards parameter
    - Calm IF activeGuards == 0, Danger IF activeGuards == 1
- Added the appropriate files and directories to  .gitignore

# IMPORTANT
FMOD Requires specific attribution as per their EULA. See *https://www.fmod.com/attribution* for details.

### CODE REVIEW

**Comment by hughbagan** [comment]
This is wild. I'd like to at least test it in my engine first to make sure the game & audio still plays with this new plugin. Judging from the changes I'm not sure if the audio volume tweens will work anymore either.

**Comment by VeryPuzzling** [comment]
Thanks! The plugin doesn't override any audio that was added through Godot's nodes or scripts. It just adds its own nodes and gdscript for interacting with FMOD.

**Comment by hughbagan** [comment]
This branch doesn't work on my machine; when I try to open the project from the menu Godot crashes. It's possible that there's a setting or files missing that haven't been committed. I see that the plugin is in alpha so it's also possible that my machine is missing a library required by FMOD. Perhaps if I install FMOD on my computer it will work. Sorry I can't be more help here. I may take a closer look later.

In the meantime @Evanator05 or anyone else, are you able to open and run the project on this branch without it crashing?

(I don't expect you to understand the backtrace but here it is anyway for the future. I can't glean much from it other than FMOD errored out somehow.)

```
hugh@brush:~/bin/godot$ ./Godot_v4.1.1-stable_linux.x86_64 
Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
OpenGL API 4.6 (Core Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3 - Compatibility - Using Device: AMD - AMD Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.42, 5.15.0-78-generic)
 
Editing project: /home/hugh/dev/godot4/albertagamejam2023
Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 570 Series (RADV POLARIS10)
hugh@brush:~/bin/godot$  
[FMOD] Saved Project Settings
WARNING: [FMOD] Failed to get icon: 0
     at: push_warning (./core/variant/variant_utility.cpp:925)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1127)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1127)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:73)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.1.1.stable.official (bd6af8e0ea69167dd0627f3bd54f9105bda0f8b5)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f510e235520] (??:0)
[2] FMOD::Studio::System::getParameterDescriptionCount(int*) const (??:0)
[3] FMODStudioEditorModule::get_project_info_from_banks() (??:0)
[4] FMODStudioEditorModule::get_project_cache() (??:0)
[5] ProjectBrowserTree::populate_browser() (??:0)
[6] ProjectBrowserWindow::initialize() (??:0)
[7] godot::MethodBindT<>::call(void*, void const* const*, long, GDExtensionCallError&) const (??:0)
[8] godot::MethodBind::bind_call(void*, void*, void const* const*, long, void*, GDExtensionCallError*) (??:0)
[9] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x47c5f18] (??:0)
[10] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x47d7128] (??:0)
[11] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x463082a] (??:0)
[12] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x12a3385] (??:0)
[13] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x118d948] (??:0)
[14] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2cdcdf1] (??:0)
[15] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d3c5c2] (??:0)
[16] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2cdef8b] (??:0)
[17] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d30456] (??:0)
[18] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x128a033] (??:0)
[19] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x118d948] (??:0)
[20] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2cdcdf1] (??:0)
[21] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d3c5c2] (??:0)
[22] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2cdef8b] (??:0)
[23] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x1dd83f1] (??:0)
[24] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x1dda13d] (??:0)
[25] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x1df4560] (??:0)
[26] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x47c4d94] (??:0)
[27] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2ccbf46] (??:0)
[28] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2ccbef4] (??:0)
[29] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d3c5df] (??:0)
[30] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d3c6ff] (??:0)
[31] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0xe46423] (??:0)
[32] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f510e21cd90] (??:0)
[33] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f510e21ce40] (??:0)
[34] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0xe777ae] (??:0)
-- END OF BACKTRACE --
================================================================
```

**Comment by Evanator05** [comment]
> This branch doesn't work on my machine; when I try to open the project from the menu Godot crashes. It's possible that there's a setting or files missing that haven't been committed. I see that the plugin is in alpha so it's also possible that my machine is missing a library required by FMOD. Perhaps if I install FMOD on my computer it will work. Sorry I can't be more help here. I may take a closer look later.
> 
> In the meantime @Evanator05 or anyone else, are you able to open and run the project on this branch without it crashing?
> 
> (I don't expect you to understand the backtrace but here it is anyway for the future. I can't glean much from it other than FMOD errored out somehow.)
> 
> ```
> hugh@brush:~/bin/godot$ ./Godot_v4.1.1-stable_linux.x86_64 
> Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
> OpenGL API 4.6 (Core Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3 - Compatibility - Using Device: AMD - AMD Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.42, 5.15.0-78-generic)
>  
> Editing project: /home/hugh/dev/godot4/albertagamejam2023
> Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
> Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 570 Series (RADV POLARIS10)
> hugh@brush:~/bin/godot$  
> [FMOD] Saved Project Settings
> WARNING: [FMOD] Failed to get icon: 0
>      at: push_warning (./core/variant/variant_utility.cpp:925)
> ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
>    at: _EDITOR_GET (editor/editor_settings.cpp:1127)
> ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
>    at: _EDITOR_GET (editor/editor_settings.cpp:1127)
> WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
>      at: _editor_init (modules/gltf/register_types.cpp:73)
> 
> ================================================================
> handle_crash: Program crashed with signal 11
> Engine version: Godot Engine v4.1.1.stable.official (bd6af8e0ea69167dd0627f3bd54f9105bda0f8b5)
> Dumping the backtrace. Please include this when reporting the bug to the project developer.
> [1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f510e235520] (??:0)
> [2] FMOD::Studio::System::getParameterDescriptionCount(int*) const (??:0)
> [3] FMODStudioEditorModule::get_project_info_from_banks() (??:0)
> [4] FMODStudioEditorModule::get_project_cache() (??:0)
> [5] ProjectBrowserTree::populate_browser() (??:0)
> [6] ProjectBrowserWindow::initialize() (??:0)
> [7] godot::MethodBindT<>::call(void*, void const* const*, long, GDExtensionCallError&) const (??:0)
> [8] godot::MethodBind::bind_call(void*, void*, void const* const*, long, void*, GDExtensionCallError*) (??:0)
> [9] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x47c5f18] (??:0)
> [10] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x47d7128] (??:0)
> [11] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x463082a] (??:0)
> [12] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x12a3385] (??:0)
> [13] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x118d948] (??:0)
> [14] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2cdcdf1] (??:0)
> [15] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d3c5c2] (??:0)
> [16] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2cdef8b] (??:0)
> [17] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d30456] (??:0)
> [18] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x128a033] (??:0)
> [19] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x118d948] (??:0)
> [20] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2cdcdf1] (??:0)
> [21] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d3c5c2] (??:0)
> [22] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2cdef8b] (??:0)
> [23] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x1dd83f1] (??:0)
> [24] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x1dda13d] (??:0)
> [25] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x1df4560] (??:0)
> [26] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x47c4d94] (??:0)
> [27] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2ccbf46] (??:0)
> [28] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2ccbef4] (??:0)
> [29] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d3c5df] (??:0)
> [30] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0x2d3c6ff] (??:0)
> [31] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0xe46423] (??:0)
> [32] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f510e21cd90] (??:0)
> [33] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f510e21ce40] (??:0)
> [34] /home/hugh/bin/godot/Godot_v4.1.1-stable_linux.x86_64() [0xe777ae] (??:0)
> -- END OF BACKTRACE --
> ================================================================
> ```

It works for me, maybe reclone your project then try the pull request?
If that works then ill merge it.

**Comment by hughbagan** [comment]
I re-cloned: the project opened on the first try, but the FMOD nodes didn't exist. Subsequent attempts to open the project just crash the engine.

**Comment by hughbagan** [comment]
I tried it again on Windows 10. First time I opened the project, same thing: nodes and classes don't exist, same error as on Linux. Second time around, the project opened and everything loaded properly. You may merge this branch if you wish. Afterward I'll only be able to work on it from my Windows desktop.

**Comment by VeryPuzzling** [comment]
I'm going to wait until FMOD for Godot is more stable (and will run on Linux) before merging this branch with Main.

**Pull request closed without merging**
